// Generated by `wit-bindgen` 0.58.0. DO NOT EDIT!
//
// This code was generated from the following packages:
//     pointerbyte:goforge@0.1.0

package pointerbyte_goforge_operations

import ()

// State observed by the host immediately before entering the guest.
// Checked flags make deadline and cancellation controls fail closed.
type ExecutionState struct {
	ClockChecked          bool
	NowUnixMilliseconds   int64
	CancellationChecked   bool
	CancellationToken     string
	CancellationRequested bool
}
