// Code generated by MockGen. DO NOT EDIT.
// Source: IClient.go

// Package client_gRPC is a generated GoMock package.
package grpc

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	grpc "google.golang.org/grpc"
)

// MockIClient is a mock of IClient interface.
type MockIClient struct {
	ctrl     *gomock.Controller
	recorder *MockIClientMockRecorder
}

// MockIClientMockRecorder is the mock recorder for MockIClient.
type MockIClientMockRecorder struct {
	mock *MockIClient
}

// NewMockIClient creates a new mock instance.
func NewMockIClient(ctrl *gomock.Controller) *MockIClient {
	mock := &MockIClient{ctrl: ctrl}
	mock.recorder = &MockIClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIClient) EXPECT() *MockIClientMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *MockIClient) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockIClientMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockIClient)(nil).Close))
}

// Connect mocks base method.
func (m *MockIClient) Connect() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Connect")
	ret0, _ := ret[0].(error)
	return ret0
}

// Connect indicates an expected call of Connect.
func (mr *MockIClientMockRecorder) Connect() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Connect", reflect.TypeOf((*MockIClient)(nil).Connect))
}

// GetConn mocks base method.
func (m *MockIClient) GetConn() *grpc.ClientConn {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetConn")
	ret0, _ := ret[0].(*grpc.ClientConn)
	return ret0
}

// GetConn indicates an expected call of GetConn.
func (mr *MockIClientMockRecorder) GetConn() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetConn", reflect.TypeOf((*MockIClient)(nil).GetConn))
}

// SetAddress mocks base method.
func (m *MockIClient) SetAddress(address string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetAddress", address)
}

// SetAddress indicates an expected call of SetAddress.
func (mr *MockIClientMockRecorder) SetAddress(address interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetAddress", reflect.TypeOf((*MockIClient)(nil).SetAddress), address)
}

// SetConn mocks base method.
func (m *MockIClient) SetConn(conn *grpc.ClientConn) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetConn", conn)
}

// SetConn indicates an expected call of SetConn.
func (mr *MockIClientMockRecorder) SetConn(conn interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetConn", reflect.TypeOf((*MockIClient)(nil).SetConn), conn)
}

// SetContext mocks base method.
func (m *MockIClient) SetContext(ctx context.Context) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetContext", ctx)
}

// SetContext indicates an expected call of SetContext.
func (mr *MockIClientMockRecorder) SetContext(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetContext", reflect.TypeOf((*MockIClient)(nil).SetContext), ctx)
}

// SetDialOptions mocks base method.
func (m *MockIClient) SetDialOptions(opts ...grpc.DialOption) {
	m.ctrl.T.Helper()
	varargs := []interface{}{}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	m.ctrl.Call(m, "SetDialOptions", varargs...)
}

// SetDialOptions indicates an expected call of SetDialOptions.
func (mr *MockIClientMockRecorder) SetDialOptions(opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetDialOptions", reflect.TypeOf((*MockIClient)(nil).SetDialOptions), opts...)
}
