#!/usr/bin/env bash
set -Eeuo pipefail

source "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/common.sh"
require_toolchain

stage=$(mktemp -d "${TMPDIR:-/tmp}/goforge-component-bindings.XXXXXX")
trap 'find "${stage}" -mindepth 1 -delete; rmdir "${stage}"' EXIT

run_componentize \
  --wit-path "${component_root}/wit" \
  --world goforge \
  bindings \
  --output "${stage}" \
  --format

mkdir -p "${guest_root}/pointerbyte_goforge_operations"
tag_wasip1_main "${stage}/wit_exports.go" "${guest_root}/wit_exports.go"
cp "${stage}/pointerbyte_goforge_operations/wit_bindings.go" \
  "${guest_root}/pointerbyte_goforge_operations/wit_bindings.go"
cp "${stage}/pointerbyte_goforge_operations/empty.s" \
  "${guest_root}/pointerbyte_goforge_operations/empty.s"

(
  cd "${guest_root}"
  GOWORK=off GOTOOLCHAIN="${go_version}" go mod tidy -go=1.25.0
)

grep -Fq 'Generated by `wit-bindgen` 0.58.0.' "${guest_root}/wit_exports.go"
grep -Fq 'pointerbyte:goforge@0.1.0' "${guest_root}/wit_exports.go"
