//go:build wasip1

// Generated by `wit-bindgen` 0.58.0. DO NOT EDIT!
//
// This code was generated from the following packages:
//     pointerbyte:goforge@0.1.0

package main

import (
	witRuntime "go.bytecodealliance.org/pkg/wit/runtime"
	"runtime"
	"unsafe"
	"wit_component/export_pointerbyte_goforge_operations"
	"wit_component/pointerbyte_goforge_operations"
)

var staticPinner = runtime.Pinner{}
var exportReturnArea = uintptr(witRuntime.Allocate(&staticPinner, (2 * 4), 4))
var syncExportPinner = runtime.Pinner{}

//go:wasmexport pointerbyte:goforge/operations@0.1.0#manifest
func wasm_export_pointerbyte_goforge_operations_manifest() uintptr {

	pinner := &syncExportPinner
	result := export_pointerbyte_goforge_operations.Manifest()
	utf8 := unsafe.Pointer(unsafe.StringData(result))
	pinner.Pin(utf8)
	*(*uint32)(unsafe.Add(unsafe.Pointer(exportReturnArea), 4)) = uint32(uint32(len(result)))
	*(*uint32)(unsafe.Add(unsafe.Pointer(exportReturnArea), 0)) = uint32(uintptr(uintptr(utf8)))
	return exportReturnArea

}

//go:wasmexport cabi_post_pointerbyte:goforge/operations@0.1.0#manifest
func wasm_export_post_return_pointerbyte_goforge_operations_manifest(result uintptr) {
	syncExportPinner.Unpin()
}

//go:wasmexport pointerbyte:goforge/operations@0.1.0#dispatch
func wasm_export_pointerbyte_goforge_operations_dispatch(arg0 uintptr, arg1 uint32, arg2 int32, arg3 int64, arg4 int32, arg5 uintptr, arg6 uint32, arg7 int32) uintptr {

	pinner := &syncExportPinner
	value := unsafe.String((*uint8)(unsafe.Pointer(arg0)), arg1)
	value0 := unsafe.String((*uint8)(unsafe.Pointer(arg5)), arg6)
	witRuntime.Unpin()
	result := export_pointerbyte_goforge_operations.Dispatch(value, pointerbyte_goforge_operations.ExecutionState{(arg2 != 0), arg3, (arg4 != 0), value0, (arg7 != 0)})
	utf8 := unsafe.Pointer(unsafe.StringData(result))
	pinner.Pin(utf8)
	*(*uint32)(unsafe.Add(unsafe.Pointer(exportReturnArea), 4)) = uint32(uint32(len(result)))
	*(*uint32)(unsafe.Add(unsafe.Pointer(exportReturnArea), 0)) = uint32(uintptr(uintptr(utf8)))
	return exportReturnArea

}

//go:wasmexport cabi_post_pointerbyte:goforge/operations@0.1.0#dispatch
func wasm_export_post_return_pointerbyte_goforge_operations_dispatch(result uintptr) {
	syncExportPinner.Unpin()
}

// Unused, but present to make the compiler happy
func main() {}
