// Code generated by MockGen. DO NOT EDIT.
// Source: config/server/grpc/config.go

// Package grpc is a generated GoMock package.
package grpc

import (
	net "net"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	grpc "google.golang.org/grpc"
)

// MockIConfig is a mock of IConfig interface.
type MockIConfig struct {
	ctrl     *gomock.Controller
	recorder *MockIConfigMockRecorder
}

// MockIConfigMockRecorder is the mock recorder for MockIConfig.
type MockIConfigMockRecorder struct {
	mock *MockIConfig
}

// NewMockIConfig creates a new mock instance.
func NewMockIConfig(ctrl *gomock.Controller) *MockIConfig {
	mock := &MockIConfig{ctrl: ctrl}
	mock.recorder = &MockIConfigMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIConfig) EXPECT() *MockIConfigMockRecorder {
	return m.recorder
}

// GetListener mocks base method.
func (m *MockIConfig) GetListener() net.Listener {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetListener")
	ret0, _ := ret[0].(net.Listener)
	return ret0
}

// GetListener indicates an expected call of GetListener.
func (mr *MockIConfigMockRecorder) GetListener() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetListener", reflect.TypeOf((*MockIConfig)(nil).GetListener))
}

// GetServer mocks base method.
func (m *MockIConfig) GetServer() *grpc.Server {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetServer")
	ret0, _ := ret[0].(*grpc.Server)
	return ret0
}

// GetServer indicates an expected call of GetServer.
func (mr *MockIConfigMockRecorder) GetServer() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetServer", reflect.TypeOf((*MockIConfig)(nil).GetServer))
}

// GracefulStop mocks base method.
func (m *MockIConfig) GracefulStop() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "GracefulStop")
}

// GracefulStop indicates an expected call of GracefulStop.
func (mr *MockIConfigMockRecorder) GracefulStop() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GracefulStop", reflect.TypeOf((*MockIConfig)(nil).GracefulStop))
}

// Register mocks base method.
func (m *MockIConfig) Register(register RegisterServiceFunc) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Register", register)
	ret0, _ := ret[0].(error)
	return ret0
}

// Register indicates an expected call of Register.
func (mr *MockIConfigMockRecorder) Register(register interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Register", reflect.TypeOf((*MockIConfig)(nil).Register), register)
}

// Serve mocks base method.
func (m *MockIConfig) Serve() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Serve")
	ret0, _ := ret[0].(error)
	return ret0
}

// Serve indicates an expected call of Serve.
func (mr *MockIConfigMockRecorder) Serve() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Serve", reflect.TypeOf((*MockIConfig)(nil).Serve))
}

// SetAddress mocks base method.
func (m *MockIConfig) SetAddress(address string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetAddress", address)
}

// SetAddress indicates an expected call of SetAddress.
func (mr *MockIConfigMockRecorder) SetAddress(address interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetAddress", reflect.TypeOf((*MockIConfig)(nil).SetAddress), address)
}

// SetListener mocks base method.
func (m *MockIConfig) SetListener(listener net.Listener) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetListener", listener)
}

// SetListener indicates an expected call of SetListener.
func (mr *MockIConfigMockRecorder) SetListener(listener interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetListener", reflect.TypeOf((*MockIConfig)(nil).SetListener), listener)
}

// Stop mocks base method.
func (m *MockIConfig) Stop() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Stop")
}

// Stop indicates an expected call of Stop.
func (mr *MockIConfigMockRecorder) Stop() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Stop", reflect.TypeOf((*MockIConfig)(nil).Stop))
}
