// Code generated by MockGen. DO NOT EDIT.
// Source: IRest.go

// Package clientHttp is a generated GoMock package.
package http

import (
	context "context"
	io "io"
	http "net/http"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockIRest is a mock of IRest interface.
type MockIRest struct {
	ctrl     *gomock.Controller
	recorder *MockIRestMockRecorder
}

// MockIRestMockRecorder is the mock recorder for MockIRest.
type MockIRestMockRecorder struct {
	mock *MockIRest
}

// NewMockIRest creates a new mock instance.
func NewMockIRest(ctrl *gomock.Controller) *MockIRest {
	mock := &MockIRest{ctrl: ctrl}
	mock.recorder = &MockIRestMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIRest) EXPECT() *MockIRestMockRecorder {
	return m.recorder
}

// Do mocks base method.
func (m *MockIRest) Do(object any) (*http.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Do", object)
	ret0, _ := ret[0].(*http.Response)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Do indicates an expected call of Do.
func (mr *MockIRestMockRecorder) Do(object interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Do", reflect.TypeOf((*MockIRest)(nil).Do), object)
}

// Get mocks base method.
func (m *MockIRest) Get(url, contentType string, object any) (*http.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", url, contentType, object)
	ret0, _ := ret[0].(*http.Response)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockIRestMockRecorder) Get(url, contentType, object interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockIRest)(nil).Get), url, contentType, object)
}

// Option mocks base method.
func (m *MockIRest) Option(url, contentType string, body io.Reader, object any) (*http.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Option", url, contentType, body, object)
	ret0, _ := ret[0].(*http.Response)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Option indicates an expected call of Option.
func (mr *MockIRestMockRecorder) Option(url, contentType, body, object interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Option", reflect.TypeOf((*MockIRest)(nil).Option), url, contentType, body, object)
}

// Patch mocks base method.
func (m *MockIRest) Patch(url, contentType string, body io.Reader, object any) (*http.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Patch", url, contentType, body, object)
	ret0, _ := ret[0].(*http.Response)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Patch indicates an expected call of Patch.
func (mr *MockIRestMockRecorder) Patch(url, contentType, body, object interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Patch", reflect.TypeOf((*MockIRest)(nil).Patch), url, contentType, body, object)
}

// Post mocks base method.
func (m *MockIRest) Post(url, contentType string, body io.Reader, object any) (*http.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Post", url, contentType, body, object)
	ret0, _ := ret[0].(*http.Response)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Post indicates an expected call of Post.
func (mr *MockIRestMockRecorder) Post(url, contentType, body, object interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Post", reflect.TypeOf((*MockIRest)(nil).Post), url, contentType, body, object)
}

// Put mocks base method.
func (m *MockIRest) Put(url, contentType string, body io.Reader, object any) (*http.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Put", url, contentType, body, object)
	ret0, _ := ret[0].(*http.Response)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Put indicates an expected call of Put.
func (mr *MockIRestMockRecorder) Put(url, contentType, body, object interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Put", reflect.TypeOf((*MockIRest)(nil).Put), url, contentType, body, object)
}

// SetContext mocks base method.
func (m *MockIRest) SetContext(ctx context.Context) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetContext", ctx)
}

// SetContext indicates an expected call of SetContext.
func (mr *MockIRestMockRecorder) SetContext(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetContext", reflect.TypeOf((*MockIRest)(nil).SetContext), ctx)
}

// SetHeaders mocks base method.
func (m *MockIRest) SetHeaders(header http.Header) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetHeaders", header)
}

// SetHeaders indicates an expected call of SetHeaders.
func (mr *MockIRestMockRecorder) SetHeaders(header interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetHeaders", reflect.TypeOf((*MockIRest)(nil).SetHeaders), header)
}

// SetRequest mocks base method.
func (m *MockIRest) SetRequest(req *http.Request) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetRequest", req)
}

// SetRequest indicates an expected call of SetRequest.
func (mr *MockIRestMockRecorder) SetRequest(req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetRequest", reflect.TypeOf((*MockIRest)(nil).SetRequest), req)
}
