// Code generated by MockGen. DO NOT EDIT.
// Source: IRestGeneric.go

// Package clientHttp is a generated GoMock package.
package http

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockIRestGeneric is a mock of IRestGeneric interface.
type MockIRestGeneric struct {
	ctrl     *gomock.Controller
	recorder *MockIRestGenericMockRecorder
}

// MockIRestGenericMockRecorder is the mock recorder for MockIRestGeneric.
type MockIRestGenericMockRecorder struct {
	mock *MockIRestGeneric
}

// NewMockIRestGeneric creates a new mock instance.
func NewMockIRestGeneric(ctrl *gomock.Controller) *MockIRestGeneric {
	mock := &MockIRestGeneric{ctrl: ctrl}
	mock.recorder = &MockIRestGenericMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIRestGeneric) EXPECT() *MockIRestGenericMockRecorder {
	return m.recorder
}

// DisableTrace mocks base method.
func (m *MockIRestGeneric) DisableTrace() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "DisableTrace")
}

// DisableTrace indicates an expected call of DisableTrace.
func (mr *MockIRestGenericMockRecorder) DisableTrace() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DisableTrace", reflect.TypeOf((*MockIRestGeneric)(nil).DisableTrace))
}

// GetGeneric mocks base method.
func (m *MockIRestGeneric) GetGeneric(ctx context.Context, input RequestGeneric) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetGeneric", ctx, input)
	ret0, _ := ret[0].(error)
	return ret0
}

// GetGeneric indicates an expected call of GetGeneric.
func (mr *MockIRestGenericMockRecorder) GetGeneric(ctx, input interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetGeneric", reflect.TypeOf((*MockIRestGeneric)(nil).GetGeneric), ctx, input)
}

// OptionGeneric mocks base method.
func (m *MockIRestGeneric) OptionGeneric(ctx context.Context, input RequestGeneric) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "OptionGeneric", ctx, input)
	ret0, _ := ret[0].(error)
	return ret0
}

// OptionGeneric indicates an expected call of OptionGeneric.
func (mr *MockIRestGenericMockRecorder) OptionGeneric(ctx, input interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "OptionGeneric", reflect.TypeOf((*MockIRestGeneric)(nil).OptionGeneric), ctx, input)
}

// PatchGeneric mocks base method.
func (m *MockIRestGeneric) PatchGeneric(ctx context.Context, input RequestGeneric) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PatchGeneric", ctx, input)
	ret0, _ := ret[0].(error)
	return ret0
}

// PatchGeneric indicates an expected call of PatchGeneric.
func (mr *MockIRestGenericMockRecorder) PatchGeneric(ctx, input interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PatchGeneric", reflect.TypeOf((*MockIRestGeneric)(nil).PatchGeneric), ctx, input)
}

// PostGeneric mocks base method.
func (m *MockIRestGeneric) PostGeneric(arg0 context.Context, arg1 RequestGeneric) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PostGeneric", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// PostGeneric indicates an expected call of PostGeneric.
func (mr *MockIRestGenericMockRecorder) PostGeneric(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PostGeneric", reflect.TypeOf((*MockIRestGeneric)(nil).PostGeneric), arg0, arg1)
}

// PutGeneric mocks base method.
func (m *MockIRestGeneric) PutGeneric(ctx context.Context, input RequestGeneric) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PutGeneric", ctx, input)
	ret0, _ := ret[0].(error)
	return ret0
}

// PutGeneric indicates an expected call of PutGeneric.
func (mr *MockIRestGenericMockRecorder) PutGeneric(ctx, input interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PutGeneric", reflect.TypeOf((*MockIRestGeneric)(nil).PutGeneric), ctx, input)
}
