// Copyright 2026 PointerByte Contributors
// SPDX-License-Identifier: Apache-2.0

package local

import (
	"context"
	"crypto"
	"crypto/aes"
	"crypto/cipher"
	"crypto/ecdh"
	"crypto/ed25519"
	"crypto/hmac"
	"crypto/rand"
	"crypto/rsa"
	"crypto/sha256"
	"crypto/x509"
	"encoding/base64"
	"encoding/hex"
	"errors"
	"fmt"
	"io"

	"github.com/PointerByte/forge-go/encrypt/common"
	"github.com/PointerByte/forge-go/encrypt/internal/trace"
	"github.com/PointerByte/forge-go/encrypt/models"
	"github.com/PointerByte/forge-go/encrypt/utilities"
	"github.com/zeebo/blake3"
)

type contextResult[T any] struct {
	value T
	err   error
}

func contextErr(ctx context.Context) error {
	if ctx == nil {
		return errors.New("context is nil")
	}
	return ctx.Err()
}

func runWithContext[T any](ctx context.Context, fn func() (T, error)) (T, error) {
	var zero T
	if err := contextErr(ctx); err != nil {
		return zero, err
	}

	done := make(chan contextResult[T], 1)
	go func() {
		value, err := fn()
		done <- contextResult[T]{value: value, err: err}
	}()

	select {
	case <-ctx.Done():
		return zero, ctx.Err()
	case result := <-done:
		return result.value, result.err
	}
}

type symmetricRepository struct{}
type keyRepository struct{}

// NewSymmetricRepository returns a SymmetricRepository implementation backed by
// the package helpers.
func NewSymmetricRepository() SymmetricRepository {
	return &symmetricRepository{}
}

// NewKeyRepository returns key-management helpers for the local backend.
func NewKeyRepository() KeyRepository {
	return &keyRepository{}
}

func (keyRepository) RotateKey(ctx context.Context, _ models.RotateKeyRequest) (data *models.KeyData, err error) {
	end := trace.Start(ctx, "local/RotateKey")
	defer end(err)
	return runWithContext(ctx, func() (*models.KeyData, error) {
		return nil, errors.New("local: key rotation is not supported")
	})
}

func (keyRepository) GetKey(ctx context.Context, _ models.GetKeyRequest) (data *models.KeyData, err error) {
	end := trace.Start(ctx, "local/GetKey")
	defer end(err)
	return runWithContext(ctx, func() (*models.KeyData, error) {
		return nil, errors.New("local: key metadata lookup is not supported")
	})
}

func (keyRepository) DeactivateKey(ctx context.Context, _ models.DeactivateKeyRequest) (err error) {
	end := trace.Start(ctx, "local/DeactivateKey")
	defer end(err)
	if err = contextErr(ctx); err != nil {
		return err
	}
	return errors.New("local: key deactivation is not supported")
}

// GenerateSymetrycKeys creates a random symmetric key and returns it in Base64
// form.
func (symmetricRepository) GenerateSymetrycKeys(ctx context.Context, input models.GenerateSymmetricKeyRequest) (data *models.KeyData, err error) {
	end := trace.Start(ctx, "local/GenerateSymetrycKeys")
	defer end(err)
	return runWithContext(ctx, func() (*models.KeyData, error) {
		if err := validateSymmetricKeySize(input.Size); err != nil {
			return nil, err
		}

		b := make([]byte, input.Size)
		if _, err := io.ReadFull(rand.Reader, b); err != nil {
			return nil, err
		}
		keyMaterial := base64.StdEncoding.EncodeToString(b)
		return &models.KeyData{
			KeyID:    keyMaterial,
			KeyRef:   keyMaterial,
			Provider: "local",
		}, nil
	})
}

// EncryptAES encrypts plaintext using AES-GCM with a Base64-encoded key and
// optional additional authenticated data.
func (symmetricRepository) EncryptAES(ctx context.Context, input models.EncryptAESRequest) (out string, err error) {
	end := trace.Start(ctx, "local/EncryptAES")
	defer end(err)
	return runWithContext(ctx, func() (string, error) {
		return encryptAES(input.SecretKey, input.Value, input.Additional)
	})
}

func encryptAES(secretKey, value string, additional *string) (string, error) {
	aesKeyBytes, err := base64.StdEncoding.DecodeString(secretKey)
	if err != nil {
		return "", fmt.Errorf("decode AES key: %w", err)
	}

	block, err := aes.NewCipher(aesKeyBytes)
	if err != nil {
		return "", fmt.Errorf("create AES cipher: %w", err)
	}

	gcm, err := cipher.NewGCM(block)
	if err != nil {
		return "", fmt.Errorf("create GCM: %w", err)
	}

	nonce := make([]byte, gcm.NonceSize())
	if _, err := rand.Read(nonce); err != nil {
		return "", fmt.Errorf("generate nonce: %w", err)
	}

	cipherText := gcm.Seal(nil, nonce, []byte(value), utilities.BytesFromOptionalString(additional))
	payload := append(nonce, cipherText...)
	return base64.StdEncoding.EncodeToString(payload), nil
}

// DecryptAES decrypts ciphertext generated by EncryptAES.
func (symmetricRepository) DecryptAES(ctx context.Context, input models.DecryptAESRequest) (out string, err error) {
	end := trace.Start(ctx, "local/DecryptAES")
	defer end(err)
	return runWithContext(ctx, func() (string, error) {
		return decryptAES(input.SecretKey, input.CipherValue, input.Additional)
	})
}

func decryptAES(secretKey, cipherValue string, additional *string) (string, error) {
	aesKeyBytes, err := base64.StdEncoding.DecodeString(secretKey)
	if err != nil {
		return "", fmt.Errorf("decode AES key: %w", err)
	}

	block, err := aes.NewCipher(aesKeyBytes)
	if err != nil {
		return "", fmt.Errorf("create AES cipher: %w", err)
	}

	gcm, err := cipher.NewGCM(block)
	if err != nil {
		return "", fmt.Errorf("create GCM: %w", err)
	}

	allBytes, err := base64.StdEncoding.DecodeString(cipherValue)
	if err != nil {
		return "", fmt.Errorf("decode Base64 ciphertext: %w", err)
	}

	if len(allBytes) < gcm.NonceSize() {
		return "", errors.New("ciphertext is too short")
	}

	nonce := allBytes[:gcm.NonceSize()]
	cipherText := allBytes[gcm.NonceSize():]
	plainText, err := gcm.Open(nil, nonce, cipherText, utilities.BytesFromOptionalString(additional))
	if err != nil {
		return "", fmt.Errorf("decrypt AES-GCM: %w", err)
	}
	return string(plainText), nil
}

type hashRepository struct{}

// NewHashRepository returns a HashRepository implementation.
func NewHashRepository() HashRepository {
	return &hashRepository{}
}

// HMAC returns a Base64-encoded HMAC-SHA256 signature.
func (hashRepository) HMAC(ctx context.Context, secretKey, message string) string {
	defer trace.Start(ctx, "local/HMAC")(nil)
	value, err := runWithContext(ctx, func() (string, error) {
		h := hmac.New(sha256.New, []byte(secretKey))
		h.Write([]byte(message))
		return base64.StdEncoding.EncodeToString(h.Sum(nil)), nil
	})
	if err != nil {
		return ""
	}
	return value
}

// Sha256Hex returns the SHA-256 digest of message encoded in hexadecimal.
func (hashRepository) Sha256Hex(ctx context.Context, message string) string {
	defer trace.Start(ctx, "local/Sha256Hex")(nil)
	value, err := runWithContext(ctx, func() (string, error) {
		hash := sha256.Sum256([]byte(message))
		return hex.EncodeToString(hash[:]), nil
	})
	if err != nil {
		return ""
	}
	return value
}

// Blake3 returns the BLAKE3 digest of message encoded in Base64.
func (hashRepository) Blake3(ctx context.Context, message string) string {
	defer trace.Start(ctx, "local/Blake3")(nil)
	value, err := runWithContext(ctx, func() (string, error) {
		hash := blake3.Sum256([]byte(message))
		return base64.StdEncoding.EncodeToString(hash[:]), nil
	})
	if err != nil {
		return ""
	}
	return value
}

type asymmetricRepository struct{}

// NewAsymmetricRepository returns an AsymmetricRepository implementation.
func NewAsymmetricRepository() AsymmetricRepository {
	return &asymmetricRepository{}
}

// GenerateRSAKeys creates an RSA key pair and returns both keys encoded in Base64.
func (asymmetricRepository) GenerateRSAKeys(ctx context.Context, input models.GenerateRSAKeyRequest) (data *models.KeyData, err error) {
	end := trace.Start(ctx, "local/GenerateRSAKeys")
	defer end(err)
	return runWithContext(ctx, func() (*models.KeyData, error) {
		if err := validateAsymmetricKeySize(input.Size); err != nil {
			return nil, err
		}

		privateKey, err := rsa.GenerateKey(rand.Reader, int(input.Size))
		if err != nil {
			return nil, err
		}
		privDer := x509.MarshalPKCS1PrivateKey(privateKey)
		priv := base64.StdEncoding.EncodeToString(privDer)
		publicKey := &privateKey.PublicKey
		publicDer := x509.MarshalPKCS1PublicKey(publicKey)
		pub := base64.StdEncoding.EncodeToString(publicDer)
		return &models.KeyData{
			KeyID:     priv,
			KeyRef:    priv,
			PublicKey: pub,
			Provider:  "local",
		}, nil
	})
}

// RSA_OAEP_Encode encrypts plaintext with RSA-OAEP using a Base64-encoded
// public key.
func (asymmetricRepository) RSA_OAEP_Encode(ctx context.Context, input models.RSAOAEPEncodeRequest) (out string, err error) {
	end := trace.Start(ctx, "local/RSA_OAEP_Encode")
	defer end(err)
	return runWithContext(ctx, func() (string, error) {
		pub, err := utilities.ParseRSAPublicKeyFromBase64(input.PublicKey)
		if err != nil {
			return "", fmt.Errorf("load public key: %w", err)
		}

		hash := sha256.New()
		cipherBytes, err := rsa.EncryptOAEP(hash, rand.Reader, pub, []byte(input.Text), nil)
		if err != nil {
			return "", fmt.Errorf("encrypt with RSA-OAEP: %w", err)
		}
		return base64.StdEncoding.EncodeToString(cipherBytes), nil
	})
}

// RSA_OAEP_Decode decrypts Base64 ciphertext with RSA-OAEP using a Base64-
// encoded private key.
func (asymmetricRepository) RSA_OAEP_Decode(ctx context.Context, input models.RSAOAEPDecodeRequest) (out string, err error) {
	end := trace.Start(ctx, "local/RSA_OAEP_Decode")
	defer end(err)
	return runWithContext(ctx, func() (string, error) {
		priv, err := utilities.ParseRSAPrivateKeyFromBase64(input.PrivateKey)
		if err != nil {
			return "", fmt.Errorf("load private key: %w", err)
		}

		encrypted, err := base64.StdEncoding.DecodeString(input.CipherText)
		if err != nil {
			return "", fmt.Errorf("decode Base64 ciphertext: %w", err)
		}

		hash := sha256.New()
		plainBytes, err := rsa.DecryptOAEP(hash, rand.Reader, priv, encrypted, nil)
		if err != nil {
			return "", fmt.Errorf("decrypt with RSA-OAEP: %w", err)
		}
		return string(plainBytes), nil
	})
}

// GenerateECDHCurveKeys creates an ECC key pair and returns both keys encoded in
// Base64.
func (asymmetricRepository) GenerateECDHCurveKeys(ctx context.Context, input models.GenerateECDHCurveKeyRequest) (data *models.KeyData, err error) {
	end := trace.Start(ctx, "local/GenerateECDHCurveKeys")
	defer end(err)
	return runWithContext(ctx, func() (*models.KeyData, error) {
		var curveImpl ecdh.Curve
		switch input.Curve {
		case common.CurveP256:
			curveImpl = ecdh.P256()
		case common.CurveP384:
			curveImpl = ecdh.P384()
		case common.CurveP521:
			curveImpl = ecdh.P521()
		default:
			return nil, fmt.Errorf("unsupported ECC curve: %q", input.Curve)
		}

		privateKey, err := curveImpl.GenerateKey(rand.Reader)
		if err != nil {
			return nil, err
		}

		privateDER, err := x509.MarshalPKCS8PrivateKey(privateKey)
		if err != nil {
			return nil, fmt.Errorf("marshal ECC private key: %w", err)
		}

		publicDER, err := x509.MarshalPKIXPublicKey(privateKey.PublicKey())
		if err != nil {
			return nil, fmt.Errorf("marshal ECC public key: %w", err)
		}

		privateEncoded := base64.StdEncoding.EncodeToString(privateDER)
		return &models.KeyData{
			KeyID:     privateEncoded,
			KeyRef:    privateEncoded,
			PublicKey: base64.StdEncoding.EncodeToString(publicDER),
			Provider:  "local",
		}, nil
	})
}

// ECDH_Encode encrypts plaintext with ECDH-derived AES-GCM using a Base64-
// encoded ECC public key.
func (repository asymmetricRepository) ECDH_Encode(ctx context.Context, input models.ECDHEncodeRequest) (out string, err error) {
	end := trace.Start(ctx, "local/ECDH_Encode")
	defer end(err)
	return runWithContext(ctx, func() (string, error) {
		recipientPublicKey, err := utilities.ParseECDHPublicKeyFromBase64(input.PublicKey)
		if err != nil {
			return "", fmt.Errorf("load public key: %w", err)
		}

		curveName, err := utilities.CurveNameFromECDH(recipientPublicKey.Curve())
		if err != nil {
			return "", err
		}

		ephemeralPrivateKey, err := recipientPublicKey.Curve().GenerateKey(rand.Reader)
		if err != nil {
			return "", fmt.Errorf("generate ephemeral key: %w", err)
		}

		sharedSecret, err := ephemeralPrivateKey.ECDH(recipientPublicKey)
		if err != nil {
			return "", fmt.Errorf("derive shared secret: %w", err)
		}

		derivedKey, err := utilities.DeriveECCAESKey(sharedSecret, curveName)
		if err != nil {
			return "", err
		}

		additional := curveName
		ciphertext, err := encryptAES(base64.StdEncoding.EncodeToString(derivedKey), input.Text, &additional)
		if err != nil {
			return "", fmt.Errorf("encrypt payload with AES-GCM: %w", err)
		}

		ephemeralPublicDER, err := x509.MarshalPKIXPublicKey(ephemeralPrivateKey.PublicKey())
		if err != nil {
			return "", fmt.Errorf("marshal ephemeral public key: %w", err)
		}

		payload, err := utilities.EncodeECCCipherPayload(utilities.ECCCipherPayload{
			Curve:              curveName,
			EphemeralPublicKey: base64.StdEncoding.EncodeToString(ephemeralPublicDER),
			Ciphertext:         ciphertext,
		})
		if err != nil {
			return "", err
		}
		return payload, nil
	})
}

// ECDH_Decode decrypts ciphertext produced by ECDH_Encode with a Base64-encoded
// ECC private key.
func (repository asymmetricRepository) ECDH_Decode(ctx context.Context, input models.ECDHDecodeRequest) (out string, err error) {
	end := trace.Start(ctx, "local/ECDH_Decode")
	defer end(err)
	return runWithContext(ctx, func() (string, error) {
		recipientPrivateKey, err := utilities.ParseECDHPrivateKeyFromBase64(input.PrivateKey)
		if err != nil {
			return "", fmt.Errorf("load private key: %w", err)
		}

		payload, err := utilities.DecodeECCCipherPayload(input.CipherText)
		if err != nil {
			return "", err
		}

		ephemeralPublicKey, err := utilities.ParseECDHPublicKeyFromBase64(payload.EphemeralPublicKey)
		if err != nil {
			return "", fmt.Errorf("load ephemeral public key: %w", err)
		}

		curveName, err := utilities.CurveNameFromECDH(recipientPrivateKey.Curve())
		if err != nil {
			return "", err
		}
		if curveName != payload.Curve {
			return "", fmt.Errorf("ecc payload curve mismatch: key uses %s, payload uses %s", curveName, payload.Curve)
		}

		sharedSecret, err := recipientPrivateKey.ECDH(ephemeralPublicKey)
		if err != nil {
			return "", fmt.Errorf("derive shared secret: %w", err)
		}

		derivedKey, err := utilities.DeriveECCAESKey(sharedSecret, payload.Curve)
		if err != nil {
			return "", err
		}

		return decryptAES(base64.StdEncoding.EncodeToString(derivedKey), payload.Ciphertext, &payload.Curve)
	})
}

type signatureRepository struct{}

// NewSignatureRepository returns a SignatureRepository implementation.
func NewSignatureRepository() SignatureRepository {
	return &signatureRepository{}
}

// GenerateEd255Keys creates an Ed25519 key pair encoded in Base64.
func (signatureRepository) GenerateEd255Keys(ctx context.Context) (data *models.KeyData, err error) {
	end := trace.Start(ctx, "local/GenerateEd255Keys")
	defer end(err)
	return runWithContext(ctx, func() (*models.KeyData, error) {
		publicKey, privateKey, err := ed25519.GenerateKey(rand.Reader)
		if err != nil {
			return nil, err
		}

		privDer, err := x509.MarshalPKCS8PrivateKey(privateKey)
		if err != nil {
			return nil, err
		}
		priv := base64.StdEncoding.EncodeToString(privDer)

		publicDer, err := x509.MarshalPKIXPublicKey(publicKey)
		if err != nil {
			return nil, err
		}
		pub := base64.StdEncoding.EncodeToString(publicDer)
		return &models.KeyData{
			KeyID:     priv,
			KeyRef:    priv,
			PublicKey: pub,
			Provider:  "local",
		}, nil
	})
}

func validateSymmetricKeySize(size common.SizeSymetrycKey) error {
	switch size {
	case common.Key128Bits, common.Key256Bits:
		return nil
	default:
		return fmt.Errorf("unsupported symmetric key size: %d", size)
	}
}

func validateAsymmetricKeySize(size common.SizeAsymetrycKey) error {
	switch size {
	case common.Key2048Bits, common.Key3072Bits, common.Key4096Bits:
		return nil
	default:
		return fmt.Errorf("unsupported asymmetric key size: %d", size)
	}
}

// SignEd25519 signs text using a Base64-encoded Ed25519 private key.
func (sr signatureRepository) SignEd25519(ctx context.Context, privateKey, text string) (out string, err error) {
	end := trace.Start(ctx, "local/SignEd25519")
	defer end(err)
	return runWithContext(ctx, func() (string, error) {
		ed25519PrivateKey, err := utilities.ParseEd25519PrivateKeyFromBase64(privateKey)
		if err != nil {
			return "", fmt.Errorf("load private key: %w", err)
		}

		signature := ed25519.Sign(ed25519PrivateKey, []byte(text))
		return base64.StdEncoding.EncodeToString(signature), nil
	})
}

// VerifyEd25519 verifies a Base64-encoded Ed25519 signature.
func (sr signatureRepository) VerifyEd25519(ctx context.Context, publicKey, text, signature string) (err error) {
	end := trace.Start(ctx, "local/VerifyEd25519")
	defer end(err)
	_, err = runWithContext(ctx, func() (struct{}, error) {
		ed25519PublicKey, err := utilities.ParseEd25519PublicKeyFromBase64(publicKey)
		if err != nil {
			return struct{}{}, fmt.Errorf("load public key: %w", err)
		}

		signatureBytes, err := base64.StdEncoding.DecodeString(signature)
		if err != nil {
			return struct{}{}, fmt.Errorf("decode signature from Base64: %w", err)
		}

		if !ed25519.Verify(ed25519PublicKey, []byte(text), signatureBytes) {
			return struct{}{}, errors.New("invalid Ed25519 signature")
		}
		return struct{}{}, nil
	})
	return err
}

// SignRSAPSS signs text using RSA-PSS and returns the signature in Base64.
func (signatureRepository) SignRSAPSS(ctx context.Context, privateKey, text string) (out string, err error) {
	end := trace.Start(ctx, "local/SignRSAPSS")
	defer end(err)
	return runWithContext(ctx, func() (string, error) {
		priv, err := utilities.ParseRSAPrivateKeyFromBase64(privateKey)
		if err != nil {
			return "", fmt.Errorf("load private key: %w", err)
		}

		hashed := sha256.Sum256([]byte(text))
		signature, err := rsa.SignPSS(rand.Reader, priv, crypto.SHA256, hashed[:], nil)
		if err != nil {
			return "", fmt.Errorf("sign with RSA-PSS: %w", err)
		}
		return base64.StdEncoding.EncodeToString(signature), nil
	})
}

// VerifyRSAPSS verifies a Base64-encoded RSA-PSS signature.
func (signatureRepository) VerifyRSAPSS(ctx context.Context, publicKey, text, signature string) (err error) {
	end := trace.Start(ctx, "local/VerifyRSAPSS")
	defer end(err)
	_, err = runWithContext(ctx, func() (struct{}, error) {
		pub, err := utilities.ParseRSAPublicKeyFromBase64(publicKey)
		if err != nil {
			return struct{}{}, fmt.Errorf("load public key: %w", err)
		}

		signatureBytes, err := base64.StdEncoding.DecodeString(signature)
		if err != nil {
			return struct{}{}, fmt.Errorf("decode signature from Base64: %w", err)
		}

		hashed := sha256.Sum256([]byte(text))
		if err := rsa.VerifyPSS(pub, crypto.SHA256, hashed[:], signatureBytes, nil); err != nil {
			return struct{}{}, fmt.Errorf("invalid RSA-PSS signature: %w", err)
		}
		return struct{}{}, nil
	})
	return err
}

// Sign_RSA_PKCS1v15_SHA256 signs data with RSA PKCS#1 v1.5 using SHA-256 and returns the
// signature in Base64.
func (signatureRepository) Sign_RSA_PKCS1v15_SHA256(ctx context.Context, privateKey, data string) (out string, err error) {
	end := trace.Start(ctx, "local/Sign_RSA_PKCS1v15_SHA256")
	defer end(err)
	return runWithContext(ctx, func() (string, error) {
		priv, err := utilities.ParseRSAPrivateKeyFromBase64(privateKey)
		if err != nil {
			return "", fmt.Errorf("load private key: %w", err)
		}

		hashed := sha256.Sum256([]byte(data))
		signature, err := rsa.SignPKCS1v15(rand.Reader, priv, crypto.SHA256, hashed[:])
		if err != nil {
			return "", fmt.Errorf("sign with RSA SHA-256: %w", err)
		}
		return base64.StdEncoding.EncodeToString(signature), nil
	})
}

// Verify_RSA_PKCS1v15_SHA256 verifies a Base64-encoded RSA PKCS#1 v1.5 SHA-256 signature.
func (signatureRepository) Verify_RSA_PKCS1v15_SHA256(ctx context.Context, data, publicKey string, signature string) (err error) {
	end := trace.Start(ctx, "local/Verify_RSA_PKCS1v15_SHA256")
	defer end(err)
	_, err = runWithContext(ctx, func() (struct{}, error) {
		pub, err := utilities.ParseRSAPublicKeyFromBase64(publicKey)
		if err != nil {
			return struct{}{}, fmt.Errorf("load public key: %w", err)
		}

		hashed := sha256.Sum256([]byte(data))
		_signature, err := base64.StdEncoding.DecodeString(signature)
		if err != nil {
			return struct{}{}, err
		}
		if err := rsa.VerifyPKCS1v15(pub, crypto.SHA256, hashed[:], []byte(_signature)); err != nil {
			return struct{}{}, fmt.Errorf("invalid RSA SHA-256 signature: %w", err)
		}
		return struct{}{}, nil
	})
	return err
}

type Repository struct {
	SymmetricRepository
	AsymmetricRepository
	KeyRepository
	SignatureRepository
	HashRepository
}

// NewRepository returns a combined repository with the main cryptographic
// capabilities exposed by this package.
func NewRepository() *Repository {
	return &Repository{
		NewSymmetricRepository(),
		NewAsymmetricRepository(),
		NewKeyRepository(),
		NewSignatureRepository(),
		NewHashRepository(),
	}
}
